name: mybot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  televerse: ^2.7.0
  googleapis: ^11.2.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  dotenv: ^4.2.0
  cron: ^0.6.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
